### ISSUE TITLE
interested in putting this in ESS?

### ISSUE THREAD

**Issue by jthaman** [jthaman/tabulate-data-frame#1]
@vspinu, @lionel-,

I'm wondering if you'd be interested in a merge of my package `pop-data-frame` into ESS. I wrote this package so that I quickly inspect large data-frames in Excel while iterating on data cleaning code in ESS. The user can interactively select a data.frame from the running session and "pop" it into the system default for viewing CSV files.

**Comment by lionel-** [comment]
We're trying to make ESS the package smaller rather than larger, so it probably wouldn't be a good place to integrate it. Small packages are easier to maintain and update.

On the other hand it might be a good fit for ESS the organisation. But no one is actively working on ESS so I think we wouldn't have time for the editorial discussions and reviews that a more open org would entail.

**Comment by jthaman** [comment]
Ok, makes sense. Hope you guys can find some help!

-John
